In [4]:
import pandas as pd

df = pd.DataFrame({
    "math":[80,70],
    "science":[90,85]
}, index=["Ravi","Amit"])

In [2]:
df.stack()

Ravi  math       80
      science    90
Amit  math       70
      science    85
dtype: int64

In [6]:
import pandas as pd
import numpy as np

df10 = pd.DataFrame({
    "emp_id":[1,2,3,3,4,5],
    "name":["Ravi","Amit","Sara","Sara","John","Anjali"],
    "department":["IT","IT","HR","HR","Finance",None],
    "salary":[50000,60000,np.nan,55000,70000,45000],
    "experience":[2,5,3,3,None,1]
})

df10

   emp_id    name department   salary  experience
0       1    Ravi         IT  50000.0         2.0
1       2    Amit         IT  60000.0         5.0
2       3    Sara         HR      NaN         3.0
3       3    Sara         HR  55000.0         3.0
4       4    John    Finance  70000.0         NaN
5       5  Anjali       None  45000.0         1.0

In [7]:
df.isna().sum()
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [8]:
df

   emp_id    name department   salary  experience
0       1    Ravi         IT  50000.0         2.0
1       2    Amit         IT  60000.0         5.0
2       3    Sara         HR      NaN         3.0
3       3    Sara         HR  55000.0         3.0
4       4    John    Finance  70000.0         NaN
5       5  Anjali       None  45000.0         1.0

In [9]:
df10['salary']=df10['salary'].fillna(df10['salary'].groupby(df10['department']).transform('mean'))

In [14]:
df10.iloc[df10.groupby('department')['salary'].transform('mean').idxmax()]

emp_id              4
name             John
department    Finance
salary        70000.0
experience        NaN
Name: 4, dtype: object