In [121]:
import pandas as pd

df = pd.DataFrame({
    'name': ['A','B','C','D'],
    'age': [20,25,30,22],
    'salary': [40000,60000,80000,50000]
})

print(df)
print(df.describe())

  name  age  salary
0    A   20   40000
1    B   25   60000
2    C   30   80000
3    D   22   50000
             age        salary
count   4.000000      4.000000
mean   24.250000  57500.000000
std     4.349329  17078.251277
min    20.000000  40000.000000
25%    21.500000  47500.000000
50%    23.500000  55000.000000
75%    26.250000  65000.000000
max    30.000000  80000.000000

In [7]:
#boolean operation of masking
df[(df['age'] > 22) | (df['salary'] >= 50000)]

  name  age  salary
1    B   25   60000
2    C   30   80000
3    D   22   50000

In [8]:
df[~(df['age'] > 25)]

  name  age  salary
0    A   20   40000
1    B   25   60000
3    D   22   50000

In [9]:
 df[df['name'].isin(['A','C'])]

  name  age  salary
0    A   20   40000
2    C   30   80000

In [10]:
df[df['name'].isin(['A','C'])]

  name  age  salary
0    A   20   40000
2    C   30   80000

In [11]:
df.loc[df['age'] > 22]

  name  age  salary
1    B   25   60000
2    C   30   80000

In [12]:
df[df['name'].str.contains('A')]

  name  age  salary
0    A   20   40000

In [ ]:
#what loc and iloc in pandas
#loc is label based indexing and iloc is integer based indexing

In [13]:
df.loc[df['age'] > 22]

  name  age  salary
1    B   25   60000
2    C   30   80000

In [14]:
df.loc[df['age'] > 22, ['name','salary']]

  name  salary
1    B   60000
2    C   80000

In [15]:
df[df['age'].between(21, 28)]

  name  age  salary
1    B   25   60000
3    D   22   50000

In [16]:
df.loc[df['age'] > 22, ['name','salary']]

  name  salary
1    B   60000
2    C   80000

In [17]:
df[df['age'].between(21, 28)]

  name  age  salary
1    B   25   60000
3    D   22   50000

In [ ]:
df[df['age'] > 22 and df['salary'] > 50000]

In [24]:
df.loc[df['age'] > 25, 'salary'] = 99999

In [25]:
df[df['department'] == 'IT']

KeyError: 'department'

In [20]:
df[df['salary'] > 50000]
# df[df['department'] == 'IT']
# df[(df['age'] > 25) & (df['city'] == 'Bangalore')]

  name  age  salary
1    B   25   60000
2    C   30   80000

In [28]:
df.head()

  name  age  salary
0    A   20   40000
1    B   25   60000
2    C   30   99999
3    D   22   50000

In [31]:
df[(df['age'] > 25) & (df['salary'] == 99999)]

  name  age  salary
2    C   30   99999

In [32]:
df[~(df['age'] > 25)]

  name  age  salary
0    A   20   40000
1    B   25   60000
3    D   22   50000

In [33]:
df[(df['age'] > 25) | (df['salary'] > 70000)]

  name  age  salary
2    C   30   99999

In [34]:
df.head()

  name  age  salary
0    A   20   40000
1    B   25   60000
2    C   30   99999
3    D   22   50000

In [38]:
df[df['name'].str.contains('A')]

  name  age  salary
0    A   20   40000

In [39]:
df.loc[df['age'] > 25, 'salary'] = 99999

In [40]:
df['name'].str.contains('A')

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [41]:
df[df['name'].str.contains('A')]

  name  age  salary
0    A   20   40000

In [42]:
df['name'].str.contains('A')

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [43]:
df[df['name'].str.contains('A', na=False)]

  name  age  salary
0    A   20   40000

In [44]:
df.query("20 < age < 30")

  name  age  salary
1    B   25   60000
3    D   22   50000

In [130]:
import pandas as pd

dft = pd.DataFrame({
    "name": ["A", "B", "A", "B"],
    "salary": [10, 20, 30, 40]
},index=['a','b','c','d'])

In [135]:
df=dft.copy()

In [137]:
df

  name  salary
a    A      10
b    B      20
c    A      30
d    B      40

In [143]:
import pandas as pd

dft = pd.DataFrame({
    "name": ["A", "B", "A", "B"],
    "salary": [10, 20, 30, 40]
},index=[1, 2, 3, 4])

In [144]:
dft.iloc[2:3, :]

  name  salary
3    A      30

In [142]:
df.loc['b':'d', :'salary']

  name  salary
b    B      20
c    A      30
d    B      40

In [131]:
df.loc[df['salary'] > 22]

  name  salary
3    A      30
4    B      40

In [126]:
dft.head()

  name  salary
1    A      10
2    B      20
3    A      30
4    B      40

In [46]:
df.groupby('name')['salary'].sum()

name
A    40
B    60
Name: salary, dtype: int64

In [47]:
df.groupby('name').count()

      salary
name
A          2
B          2

In [49]:
df.groupby('name')['salary'].mean()

name
A    20.0
B    30.0
Name: salary, dtype: float64

In [52]:
df.isnull()
df.dropna()
df.fillna(0)
df.fillna(method="ffill")

C:\Users\cheth\AppData\Local\Temp\ipykernel_37608\2215468587.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

  name  salary
0    A      10
1    B      20
2    A      30
3    B      40

In [ ]:
# Merge (like SQL join)
# pd.merge(df1, df2, on="id")
# Concat (stack data)
# pd.concat([df1, df2])
# Apply Functions

# Custom logic on data.

# df["salary"].apply(lambda x: x*2)
# Column Operations
# df["new"] = df["salary"] * 2
# df.drop("salary", axis=1)
# df.rename(columns={"old":"new"})

In [58]:
df1 = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "name": ["Ravi", "Amit", "John", "Sara"],
    "salary": [50000, 60000, 55000, 70000]
})

print(df1)

   emp_id  name  salary
0       1  Ravi   50000
1       2  Amit   60000
2       3  John   55000
3       4  Sara   70000

In [59]:
df2 = pd.DataFrame({
    "emp_id": [1, 2, 4, 5],
    "department": ["HR", "IT", "Finance", "Marketing"]
})

print(df2)

   emp_id department
0       1         HR
1       2         IT
2       4    Finance
3       5  Marketing

In [ ]:
df3=pd.merge(df1, df2, on="emp_id", how="inner")

   emp_id  name  salary department
0       1  Ravi   50000         HR
1       2  Amit   60000         IT
2       4  Sara   70000    Finance

In [61]:
pd.merge(df1, df2, on="emp_id", how="inner")

   emp_id  name  salary department
0       1  Ravi   50000         HR
1       2  Amit   60000         IT
2       4  Sara   70000    Finance

In [62]:
pd.merge(df1, df2, on="emp_id", how="left")

   emp_id  name  salary department
0       1  Ravi   50000         HR
1       2  Amit   60000         IT
2       3  John   55000        NaN
3       4  Sara   70000    Finance

In [63]:
pd.merge(df1, df2, on="emp_id", how="right")

   emp_id  name   salary department
0       1  Ravi  50000.0         HR
1       2  Amit  60000.0         IT
2       4  Sara  70000.0    Finance
3       5   NaN      NaN  Marketing

In [64]:
pd.merge(df1, df2, on="emp_id", how="right")

   emp_id  name   salary department
0       1  Ravi  50000.0         HR
1       2  Amit  60000.0         IT
2       4  Sara  70000.0    Finance
3       5   NaN      NaN  Marketing

In [65]:
import pandas as pd

df_emp = pd.DataFrame({
    "emp_id": [1,2,3,4,5],
    "name": ["Ravi","Amit","Sara","John","Neha"]
})

df_dept = pd.DataFrame({
    "emp_id": [1,2,4],
    "department": ["HR","IT","Finance"]
})

In [66]:
df_emp

   emp_id  name
0       1  Ravi
1       2  Amit
2       3  Sara
3       4  John
4       5  Neha

In [67]:
df_dept

   emp_id department
0       1         HR
1       2         IT
2       4    Finance

In [70]:
pd.merge(df_emp, df_dept, on="emp_id", how="right")

   emp_id  name department
0       1  Ravi         HR
1       2  Amit         IT
2       4  John    Finance

In [71]:
import pandas as pd

df_emp = pd.DataFrame({
    "emp_id": [1,2,3,4,5],
    "name": ["Ravi","Amit","Sara","John","Neha"]
})

df_dept = pd.DataFrame({
    "emp_id": [1,2,4],
    "department": ["HR","IT","Finance"]
})

In [76]:
mergedd_df=pd.merge(df_emp,df_dept,on="emp_id", how="left")

In [ ]:
filter_Df=mergedd_df[mergedd_df['department'].isnull()]
filter_Df[['name','department']]

   name department
2  Sara        NaN
4  Neha        NaN

In [81]:
mergedd_df['salary']=[50000, 60000, 55000, 70000, 65000]

In [83]:
mergedd_df.groupby('department')['salary'].max()

department
Finance    70000
HR         50000
IT         60000
Name: salary, dtype: int64

In [87]:
# Customers Who Ordered All Products

orders = pd.DataFrame({
    "customer": ["A","A","B","B","C"],
    "product": ["pen","book","pen","pencil","book"]
})

products = pd.DataFrame({
    "product": ["pen","book","pencil"]
})

In [89]:
who_orderall_products= pd.merge(orders,products,on='product', how='inner')
who_orderall_products.groupby('customer')['product'].nunique()

customer
A    2
B    2
C    1
Name: product, dtype: int64

In [90]:
df = pd.DataFrame({
    "department":["IT","IT","HR","HR"],
    "gender":["M","F","M","F"],
    "salary":[50000,80000,60000,55000]
})

df.groupby(["department","gender"])["salary"].mean()

department  gender
HR          F         55000.0
            M         60000.0
IT          F         80000.0
            M         50000.0
Name: salary, dtype: float64

In [91]:
df = pd.DataFrame({
    "department":["IT","IT","HR","HR"],
    "gender":["M","F","M","F"],
    "salary":[50000,80000,60000,55000]
})

df.groupby(["department","gender"])["salary"].mean().reset_index()

  department gender   salary
0         HR      F  55000.0
1         HR      M  60000.0
2         IT      F  80000.0
3         IT      M  50000.0

In [ ]:
# highest salary of employee per department
df.loc[df.groupby("department")["salary"].idxmax()]

  department gender  salary
2         HR      M   60000
1         IT      F   80000

In [94]:
# AVG(salary) OVER (PARTITION BY department)
df["avg_salary"] = df.groupby("department")["salary"].transform("mean")

In [93]:
# RANK() OVER (PARTITION BY department ORDER BY salary DESC)
df["rank"] = df.groupby("department")["salary"].rank(ascending=False)

In [ ]:
# RANK() OVER (PARTITION BY department ORDER BY salary DESC)

In [97]:
df['rank']=df.groupby("department")["salary"].rank(ascending=False)
df

  department gender  salary  rank  avg_salary  running_total
0         IT      M   50000   2.0     65000.0          50000
1         IT      F   80000   1.0     65000.0         130000
2         HR      M   60000   1.0     57500.0          60000
3         HR      F   55000   2.0     57500.0         115000

In [98]:
# SUM(salary) OVER (PARTITION BY department ORDER BY id)
df["running_total"] = df.groupby("department")["salary"].cumsum()
df

  department gender  salary  rank  avg_salary  running_total
0         IT      M   50000   2.0     65000.0          50000
1         IT      F   80000   1.0     65000.0         130000
2         HR      M   60000   1.0     57500.0          60000
3         HR      F   55000   2.0     57500.0         115000

In [ ]:
# LAG(salary)

In [100]:
df["prev_salary"] = df.groupby("department")["salary"].shift(1)
df

  department gender  salary  rank  avg_salary  running_total  prev_salary
0         IT      M   50000   2.0     65000.0          50000          NaN
1         IT      F   80000   1.0     65000.0         130000      50000.0
2         HR      M   60000   1.0     57500.0          60000          NaN
3         HR      F   55000   2.0     57500.0         115000      60000.0

In [102]:
#time series data

In [101]:
df["moving_avg"] = df["salary"].rolling(2).mean()

In [106]:
df = pd.DataFrame({
    "name": ["Ravi","Amit"],
    "math":[80,70],
    "science":[90,85],
    "english":[75,88]
})

In [108]:
df

   name  math  science  english
0  Ravi    80       90       75
1  Amit    70       85       88

In [107]:
df.melt(id_vars="name", var_name="subject", value_name="score")

   name  subject  score
0  Ravi     math     80
1  Amit     math     70
2  Ravi  science     90
3  Amit  science     85
4  Ravi  english     75
5  Amit  english     88

In [111]:
import pandas as pd
df5["percent"] = (
    df5["marks"] /
    df5.groupby("name")["marks"].transform("sum")
)

df5

   name  subject  marks   percent
0  Ravi     math     80  0.470588
1  Ravi  science     90  0.529412
2  Amit     math     70  0.451613
3  Amit  science     85  0.548387

In [116]:
import pandas as pd

df5 = pd.DataFrame({
    "name": ["Ravi","Ravi","Amit","Amit"],
    "subject": ["math","science","math","science"],
    "marks": [80,90,70,85]
})

df5

   name  subject  marks
0  Ravi     math     80
1  Ravi  science     90
2  Amit     math     70
3  Amit  science     85

In [118]:
df5.melt(id_vars="name", var_name="subject", value_name="score")

   name  subject    score
0  Ravi  subject     math
1  Ravi  subject  science
2  Amit  subject     math
3  Amit  subject  science
4  Ravi    marks       80
5  Ravi    marks       90
6  Amit    marks       70
7  Amit    marks       85

In [119]:
df5.pivot(index="name", columns="subject", values="marks")

subject  math  science
name
Amit       70       85
Ravi       80       90