In [2]:
import pandas as pd
import numpy as np

In [ ]:
#what is pandas: 
#Pandas is a powerful Python library for data manipulation and analysis. It provides data structures like DataFrames and Series, which are designed to handle structured data efficiently. Pandas is widely used in data science, finance, and analytics for tasks such as data cleaning, transformation, aggregation, and visualization.

In [ ]:
#what is numpy?
#NumPy is a fundamental Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, and machine learning applications due to its performance and ease of use.

In [34]:
import pandas as pd 

li=[1,2,3,4,5]
s3=pd.Series(li)
print(s[5-1])
li2=["s","t","r","i","n","g"]
s4=pd.Series(li2)
s1[4]

5

'n'

In [ ]:
for i in s1:
    if i=="n":
        print("found")
        break

In [35]:
import pandas as pd
s = pd.Series([10,20,30])
s2=pd.Series([40,50,60])
df3=pd.DataFrame([s,s2,s3,s4])
print(df3)

      0     1     2    3    4    5
0  10.0  20.0  30.0  NaN  NaN  NaN
1  40.0  50.0  60.0  NaN  NaN  NaN
2   1.0   2.0   3.0  4.0  5.0  NaN
3     s     t     r    i    n    g

In [37]:
df4=pd.DataFrame({"col1":s1,"col2":s2,"col3":s3,"col4":s4})
print(df4)

  col1  col2  col3 col4
0    s  40.0   1.0    s
1    t  50.0   2.0    t
2    r  60.0   3.0    r
3    i   NaN   4.0    i
4    n   NaN   5.0    n
5    g   NaN   NaN    g

In [41]:
df4.iloc[:2,:2]

  col1  col2
0    s  40.0
1    t  50.0

In [ ]:
np.array([1,2,3,4,5])

In [16]:
pd.DataFrame(np.array([[1,2],[3,4]]))

   0  1
0  1  2
1  3  4

In [42]:
data = np.array([(1,'A'),(2,'B')],
                dtype=[('id','i4'),('name','U10')])
df = pd.DataFrame(data)
print(df)

   id name
0   1    A
1   2    B

In [9]:
df2=pd.DataFrame(data={'id':[1,2],'name':['A','B']})
print(df2)

   id name
0   1    A
1   2    B

In [44]:
df2[['id','name']]

   id name
0   1    A
1   2    B

In [ ]:
#masking and filtering
df2[df2['id']==2]

   id name
1   2    B

In [13]:
print(df2[df2['id']<2])

   id name
0   1    A

In [ ]:
#fill NaN values with 0
df3=pd.DataFrame({
    'a': pd.Series([1,2,3]),
    'b': pd.Series([4,5])
})
df3.fillna(0, inplace=True)
df3

   a    b
0  1  4.0
1  2  5.0
2  3  0.0

In [21]:
data=np.array(np.random.rand(3,2),dtype='float32')
df5=pd.DataFrame(data,columns=['col1','col2'])
print(df5)

       col1      col2
0  0.830303  0.981812
1  0.279265  0.108597
2  0.794081  0.883067